INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (1, 'Triple-buffered');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (2, 'needs-based');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (3, 'superstructure');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (4, 'pricing structure');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (5, 'human-resource');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (6, 'Sharable');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (7, 'Face to face');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (8, 'intangible');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (9, 'neutral');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (10, 'knowledge user');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (11, 'Inverse');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (12, 'policy');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (13, 'Profit-focused');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (14, 'content-based');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (15, 'synergy');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (16, 'Intuitive');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (17, 'capability');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (18, 'bi-directional');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (19, 'Down-sized');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (20, 'Phased');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (21, 'mobile');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (22, 'De-engineered');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (23, 'disintermediate');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (24, 'Grass-roots');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (25, 'homogeneous');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (26, 'Cross-platform');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (27, 'core');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (28, 'tertiary');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (29, 'groupware');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (30, 'attitude');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (31, 'ability');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (32, 'intermediate');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (33, 'Upgradable');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (34, 'emulation');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (35, 'secondary');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (36, 'artificial intelligence');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (37, 'approach');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (38, 'Networked');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (39, 'reciprocal');
INSERT INTO public.motsclefs (mtc_id, mtc_nom) VALUES (40, 'knowledge base');
