INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (1, 4, 12, 'Balanced impactful initiative', '2021-02-01');
INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (2, 10, 11, 'Realigned national knowledge base', '2021-09-19');
INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (3, 1, 12, 'Grass-roots zero tolerance superstructure', '2021-10-17');
INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (4, 11, 4, 'Networked cohesive website', '2021-05-13');
INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (5, 19, 10, 'Vision-oriented systematic budgetary management', '2021-11-07');
INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (6, 16, 12, 'Cloned demand-driven Graphical User Interface', '2021-06-16');
INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (7, 5, 1, 'Vision-oriented well-modulated hierarchy', '2021-09-21');
INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (8, 2, 12, 'Streamlined didactic ability', '2021-07-03');
INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (9, 19, 13, 'Assimilated holistic Graphic Interface', '2021-05-19');
INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (10, 11, 10, 'Compatible coherent process improvement', '2021-03-12');
INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (11, 4, 15, 'Automated full-range algorithm', '2021-06-07');
INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (12, 9, 15, 'Front-line dynamic parallelism', '2021-02-24');
INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (13, 14, 11, 'Distributed regional functionalities', '2021-08-11');
INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (14, 13, 8, 'Team-oriented zero defect focus group', '2021-03-16');
INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (15, 12, 11, 'Configurable mission-critical info-mediaries', '2021-11-27');
INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (16, 1, 7, 'Pre-emptive zero defect Graphical User Interface', '2021-02-09');
INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (17, 5, 13, 'Progressive exuding forecast', '2021-03-12');
INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (18, 1, 6, 'Reactive intermediate methodology', '2021-05-10');
INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (19, 11, 6, 'Enterprise-wide contextually-based parallelism', '2021-09-08');
INSERT INTO public.aevalue (eval_id, eval_abn_id, eval_objet, eval_justification, eval_date_justification) VALUES (20, 3, 2, 'Fully-configurable 3rd generation secured line', '2021-05-09');
