INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (1, 16, 'Future-proofed bandwidth-monitored capability');
INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (2, 4, 'Distributed radical capacity');
INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (3, 2, 'Diverse client-driven secured line');
INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (4, 13, 'Optional discrete challenge');
INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (5, 3, 'Synergized disintermediate secured line');
INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (6, 4, 'Front-line human-resource focus group');
INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (7, 14, 'Re-contextualized 6th generation protocol');
INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (8, 17, 'Assimilated logistical protocol');
INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (9, 17, 'Customer-focused zero defect customer loyalty');
INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (10, 11, 'Grass-roots clear-thinking middleware');
INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (11, 20, 'Pre-emptive value-added adapter');
INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (12, 17, 'Up-sized stable attitude');
INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (13, 20, 'Programmable 4th generation emulation');
INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (14, 6, 'Enterprise-wide intermediate methodology');
INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (15, 8, 'Down-sized next generation framework');
INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (16, 20, 'Front-line optimizing data-warehouse');
INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (17, 2, 'Reduced dedicated methodology');
INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (18, 4, 'Multi-tiered heuristic instruction set');
INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (19, 17, 'Multi-tiered even-keeled installation');
INSERT INTO public.notification (ntf_id, ntf_abn_id, ntf_contenu) VALUES (20, 15, 'Diverse fresh-thinking adapter');
