INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (1, 'Industrial', 'en attente');
INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (2, 'Garden', 'en attente');
INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (3, 'Sports', 'en attente');
INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (4, 'Music', 'en attente');
INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (5, 'Festival', 'valide');
INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (6, 'Clothing', 'valide');
INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (7, 'IT', 'valide');
INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (8, 'Outdoors', 'valide');
INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (9, 'Shoes', 'non valide');
INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (10, 'Health', 'non valide');
INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (11, 'Movies', 'non valide');
INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (12, 'Books', 'non valide');
INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (13, 'Automotive', 'en attente');
INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (14, 'Baby', 'en attente');
INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (15, 'IA', 'en attente');
INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (16, 'Jewelry', 'non valide');
INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (17, 'Algorithm', 'non valide');
INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (18, 'Cat', 'valide');
INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (19, 'Mazette', 'valide');
INSERT INTO public.domaine (dom_id, dom_nom, dom_etat) VALUES (20, 'Gandalf', 'valide');
